### PR TITLE
Update ember and friends to 2.8, add working unit tests

### PR DESCRIPTION
**Pull request by tylerturdenpants**
- Updated `ember` to `2.8`
- Updated addon project to `ember-cli:2.8` 
- Remove moment from bower
- Added `ember-cli-moment-shim`

### CODE REVIEW

**Comment by ChrisHonniball** [comment]
@tylerturdenpants any interest in being added as a collaborator?

**Comment by tylerturdenpants** [comment]
Sure!  I have some string manipulation additions to add from my own project

**Comment by tylerturdenpants** [comment]
I've also enabled Travis CI to build off my fork.  The addon should work all the way back to 1.13

**Comment by ChrisHonniball** [comment]
Thanks! I appreciate the help. Sometimes it's difficult to get to the side projects. Even though I've been using this on my production Apps I just haven't had the time to dedicate to updating them all.

**Pull request merged**
